from __future__ import annotations

from collections.abc import Iterable

from gradio.themes.base import Base
from gradio.themes.utils import colors, fonts, sizes


class Beeuty(Base):
    def __init__(
        self,
        *,
        primary_hue: colors.Color | str = colors.Color(
            c100="#fef9c3",
            c200="#fef08a",
            c300="#fde047",
            c400="#fbce50",
            c50="#fefce8",
            c500="#eab308",
            c600="#daa520",
            c700="#a16207",
            c800="#854d0e",
            c900="#713f12",
            c950="#653b12",
        ),
        secondary_hue: colors.Color | str = colors.Color(
            c100="#fef3c7",
            c200="#fde68a",
            c300="#fbce50",
            c400="#fbbf24",
            c50="#fffbeb",
            c500="#daa520",
            c600="#df7a07",
            c700="#b45309",
            c800="#92400e",
            c900="#78350f",
            c950="#6c370f",
        ),
        neutral_hue: colors.Color | str = colors.Color(
            c100="#d8bbf7",
            c200="#dac0f7",
            c300="#bb8eec",
            c400="#a669e2",
            c50="#faf5ff",
            c500="#944ed4",
            c600="#8537cd",
            c700="#7e22ce",
            c800="#562183",
            c900="#3f225d",
            c950="#160b23",
        ),
        spacing_size: sizes.Size | str = sizes.spacing_sm,
        radius_size: sizes.Size | str = sizes.radius_lg,
        text_size: sizes.Size | str = sizes.text_md,
        font: fonts.Font | str | Iterable[fonts.Font | str] = (
            "Optima",
            "Candara",
            "Noto Sans",
            "source-sans-pro",
            "sans-serif",
        ),
        font_mono: fonts.Font | str | Iterable[fonts.Font | str] = (
            fonts.GoogleFont("IBM Plex Mono"),
            "ui-monospace",
            "Consolas",
            "monospace",
        ),
    ):
        super().__init__(
            primary_hue=primary_hue,
            secondary_hue=secondary_hue,
            neutral_hue=neutral_hue,
            spacing_size=spacing_size,
            radius_size=radius_size,
            text_size=text_size,
            font=font,
            font_mono=font_mono,
        )
        self.name = "beeuty"
        super().set(
            accordion_text_color="*neutral_950",
            accordion_text_color_dark="*neutral_50",
            background_fill_primary="*primary_600",
            background_fill_primary_dark="*primary_500",
            background_fill_secondary="*primary_500",
            background_fill_secondary_dark="*secondary_900",
            block_background_fill="*primary_300",
            block_background_fill_dark="*primary_800",
            block_border_width="0px",
            block_border_width_dark="1px",
            block_label_background_fill="*primary_200",
            block_label_background_fill_dark="*primary_700",
            block_label_margin="1px",
            block_label_text_color="*primary_950",
            block_label_text_size="*text_md",
            block_label_text_weight="600",
            block_shadow="*primary_400 0px 0px 3px 0px",
            block_title_text_color="*primary_800",
            block_title_text_size="*text_md",
            block_title_text_weight="600",
            body_background_fill_dark="*background_fill_secondary",
            body_text_color="*neutral_900",
            body_text_color_dark="*secondary_200",
            body_text_color_subdued="*neutral_800",
            body_text_color_subdued_dark="*neutral_200",
            border_color_accent="*primary_900",
            border_color_primary="*neutral_800",
            border_color_primary_dark="*secondary_600",
            button_border_width="1px",
            button_cancel_background_fill="*button_primary_background_fill",
            button_cancel_background_fill_dark="*button_primary_background_fill",
            button_cancel_background_fill_hover="*button_primary_background_fill_hover",
            button_cancel_background_fill_hover_dark="*button_primary_background_fill_hover",
            button_cancel_border_color="*button_secondary_border_color",
            button_cancel_border_color_dark="*button_secondary_border_color",
            button_cancel_text_color="*button_secondary_text_color",
            button_primary_background_fill="linear-gradient(180deg, *primary_50 0%, *primary_200 50%, *primary_300 50%, *primary_200 100%)",
            button_primary_background_fill_dark="linear-gradient(180deg, *primary_400 0%, *primary_500 50%, *primary_600 50%, *primary_500 100%)",
            button_primary_background_fill_hover="linear-gradient(180deg, *primary_100 0%, *primary_200 50%, *primary_300 50%, *primary_200 100%)",
            button_primary_background_fill_hover_dark="linear-gradient(180deg, *primary_400 0%, *primary_500 50%, *primary_600 50%, *primary_500 100%)",
            button_primary_text_color="*primary_800",
            button_primary_text_color_dark="*primary_100",
            button_secondary_background_fill="*button_primary_background_fill",
            button_secondary_background_fill_dark="*button_primary_background_fill",
            button_secondary_background_fill_hover="*button_primary_background_fill_hover",
            button_secondary_background_fill_hover_dark="*button_primary_background_fill_hover",
            button_secondary_text_color="*secondary_950",
            button_secondary_text_color_dark="*secondary_50",
            button_primary_shadow_hover="0px 5px 0px 0px *primary_400;",
            button_primary_shadow="0px 3px 0px 0px *primary_400;",
            button_primary_shadow_active="0px 2px 0px 0px *primary_400;",
            button_secondary_shadow_hover="0px 5px 0px 0px *primary_300;",
            button_secondary_shadow="0px 3px 0px 0px *primary_300;",
            button_secondary_shadow_active="0px 2px 0px 0px *primary_300;",
            checkbox_background_color_dark="*primary_600",
            checkbox_border_width="0px",
            checkbox_label_background_fill="*button_secondary_background_fill",
            checkbox_label_background_fill_dark="*button_secondary_background_fill",
            checkbox_label_background_fill_hover="*button_secondary_background_fill_hover",
            checkbox_label_background_fill_hover_dark="*button_secondary_background_fill_hover",
            checkbox_label_border_width="1px",
            code_background_fill="*neutral_300",
            code_background_fill_dark="*neutral_600",
            color_accent="*neutral_200",
            color_accent_soft="*primary_200",
            color_accent_soft_dark="*neutral_800",
            input_background_fill="linear-gradient(0deg, *primary_300 0%, white 100%)",
            input_background_fill_dark="*secondary_600",
            input_border_color_focus_dark="*primary_400",
            input_border_width="1px",
            link_text_color_active="*neutral_500",
            link_text_color_visited="*neutral_500",
            link_text_color="*secondary_700",
            link_text_color_dark="*secondary_300",
            link_text_color_hover="*secondary_800",
            panel_border_width="1px",
            slider_color="*primary_400",
            table_even_background_fill="*primary_100",
            table_even_background_fill_dark="*neutral_700",
            table_odd_background_fill_dark="*neutral_800",
        )
