from __future__ import annotations

from collections.abc import Iterable

from gradio.themes.base import Base
from gradio.themes.utils import colors, fonts, sizes


class Beeuty(Base):
    def __init__(
        self,
        *,
        primary_hue: colors.Color | str = colors.Color(
            c100="rgba(255, 233.38983050847455, 0, 1)", 
            c200="#fde047", c300="#ffca05", 
            c400="#f6a600", c50="#fefce8", c500="#eab308", c600="#ca8a04", 
            c700="#a16207", c800="rgba(135.5466735839844, 73.40411437758955, 17.635150987235207, 1)", 
            c900="rgba(36.125000000000014, 17.312185133429974, 0.38065175351693403, 1)", 
            c950="rgba(0, 0, 0, 1)"
        ),
        secondary_hue: colors.Color | str = colors.Color(
            c100="#fef9c3", c200="#fef08a", c300="#fde047", 
            c400="#fbce50", c50="#fefce8", c500="#eab308", c600="#daa520", 
            c700="#a16207", c800="#854d0e", 
            c900="rgba(29.38165283203124, 28.374719896327637, 0.18059769662660624, 1)", 
            c950="rgba(0, 0, 0, 1)"
        ),
        neutral_hue: colors.Color | str = colors.purple,
        spacing_size: sizes.Size | str = sizes.spacing_sm,
        radius_size: sizes.Size | str = sizes.radius_lg,
        text_size: sizes.Size | str = sizes.text_md,
        font: fonts.Font | str | Iterable[fonts.Font | str] = (
            "Optima",
            "Candara",
            "Noto Sans",
            "source-sans-pro",
            "sans-serif",
        ),
        font_mono: fonts.Font | str | Iterable[fonts.Font | str] = (
            fonts.GoogleFont("IBM Plex Mono"),
            "ui-monospace",
            "Consolas",
            "monospace",
        ),
    ):
        super().__init__(
            primary_hue=primary_hue,
            secondary_hue=secondary_hue,
            neutral_hue=neutral_hue,
            spacing_size=spacing_size,
            radius_size=radius_size,
            text_size=text_size,
            font=font,
            font_mono=font_mono,
        )
        self.name = "beeuty"
        super().set(
            accordion_text_color='*primary_200',
            accordion_text_color_dark='*primary_200',
            background_fill_primary='*primary_950',
            background_fill_primary_dark='*primary_800',
            background_fill_secondary='*secondary_950',
            background_fill_secondary_dark='*secondary_950',
            block_background_fill='*secondary_900',
            block_background_fill_dark='*secondary_950',
            block_border_width="0px",
            block_border_width_dark="1px",
            block_border_color='*primary_50',
            block_info_text_color='*primary_300',
            block_info_text_color_dark='*secondary_200',
            block_label_background_fill='*secondary_950',
            block_label_background_fill_dark='*primary_950',
            block_label_margin="1px",
            block_label_text_color='*primary_200',
            block_label_text_color_dark='*primary_200',
            block_label_text_size="*text_md",
            block_label_text_weight="600",
            block_shadow="*primary_400 0px 0px 3px 0px",
            block_title_background_fill='*primary_100',
            block_title_background_fill_dark='*secondary_900',
            block_title_border_color='*secondary_50',
            block_title_border_color_dark='*primary_950',
            block_title_text_color='*primary_900',
            block_title_text_color_dark='*secondary_200',
            block_title_padding='*block_label_padding',
            block_title_radius='*radius_xs',
            block_title_text_size="*text_md",
            block_title_text_weight="600",
            body_background_fill='*primary_950',
            body_background_fill_dark='*secondary_950',
            body_text_color='*secondary_200',
            body_text_color_dark="*secondary_200",
            body_text_color_subdued='*neutral_700',
            body_text_color_subdued_dark="*neutral_200",
            border_color_accent="*primary_900",
            border_color_primary='*secondary_950',
            border_color_primary_dark='*secondary_200',
            button_border_width="1px",
            button_cancel_background_fill="*button_primary_background_fill",
            button_cancel_background_fill_dark="*button_primary_background_fill",
            button_cancel_background_fill_hover="*button_primary_background_fill_hover",
            button_cancel_background_fill_hover_dark="*button_primary_background_fill_hover",
            button_cancel_border_color="*button_secondary_border_color",
            button_cancel_border_color_dark="*button_secondary_border_color",
            button_cancel_text_color="*button_secondary_text_color",
            button_primary_background_fill="linear-gradient(180deg, *primary_50 0%, *primary_200 50%, *primary_300 50%, *primary_200 100%)",
            button_primary_background_fill_dark="linear-gradient(180deg, *primary_400 0%, *primary_500 50%, *primary_600 50%, *primary_500 100%)",
            button_primary_background_fill_hover="linear-gradient(180deg, *primary_100 0%, *primary_200 50%, *primary_300 50%, *primary_200 100%)",
            button_primary_background_fill_hover_dark="linear-gradient(180deg, *primary_400 0%, *primary_500 50%, *primary_600 50%, *primary_500 100%)",
            button_primary_text_color="*primary_800",
            button_primary_text_color_dark="*primary_100",
            button_secondary_background_fill="*button_primary_background_fill",
            button_secondary_background_fill_dark="*button_primary_background_fill",
            button_secondary_background_fill_hover="*button_primary_background_fill_hover",
            button_secondary_background_fill_hover_dark="*button_primary_background_fill_hover",
            button_secondary_text_color="*secondary_700",
            button_secondary_text_color_dark="*secondary_50",
            button_primary_shadow_hover="0px 5px 0px 0px *primary_400;",
            button_primary_shadow="0px 3px 0px 0px *primary_400;",
            button_primary_shadow_active="0px 2px 0px 0px *primary_400;",
            button_secondary_shadow_hover="0px 5px 0px 0px *primary_300;",
            button_secondary_shadow="0px 3px 0px 0px *primary_300;",
            button_secondary_shadow_active="0px 2px 0px 0px *primary_300;",
            checkbox_background_color='*block_background_fill',
            checkbox_background_color_dark='*block_background_fill',
            checkbox_background_color_focus='*neutral_600',
            checkbox_background_color_focus_dark='*neutral_600',
            checkbox_border_width="0px",
            checkbox_label_background_fill="*button_secondary_background_fill",
            checkbox_label_background_fill_dark="*button_secondary_background_fill",
            checkbox_label_background_fill_hover="*button_secondary_background_fill_hover",
            checkbox_label_background_fill_hover_dark="*button_secondary_background_fill_hover",
            checkbox_label_border_width="1px",
            code_background_fill='*neutral_950',
            code_background_fill_dark='*neutral_950',
            color_accent='*neutral_300',
            color_accent_soft="*neutral_800",
            color_accent_soft_dark="*neutral_800",
            input_background_fill='*primary_900',
            input_background_fill_dark='*secondary_950',
            input_border_color_focus='*primary_300',
            input_border_color_focus_dark='*secondary_300',
            input_border_width="1px",
            input_placeholder_color='*neutral_200',
            input_shadow='*primary_950',
            input_shadow_dark='*secondary_950',
            link_text_color_active="*neutral_500",
            link_text_color_visited="*neutral_500",
            link_text_color='*secondary_600',
            link_text_color_dark="*secondary_300",
            link_text_color_hover="*secondary_800",
            panel_background_fill='*primary_950',
            panel_border_color='*primary_200',
            panel_border_width="1px",
            slider_color='*primary_200',
            table_border_color='*primary_200',
            table_border_color_dark='*secondary_200',
            table_even_background_fill='*primary_400',
            table_even_background_fill_dark='*secondary_500',
            table_odd_background_fill='*primary_900',
            table_odd_background_fill_dark='*secondary_950',
            table_radius='*radius_md',
            section_header_text_weight='600',
        )
