from .base import Base
from .utils import colors, size


class Glass(Base):
    def __init__(
        self,
        *,
        hue: colors.Color = colors.stone,
        spacing_size: size.Size = size.spacing_sm,
        radius_size: size.Size = size.radius_sm,
        text_size: size.Size = size.text_sm,
    ):
        super().__init__(
            primary_hue=hue,
            secondary_hue=hue,
            neutral_hue=hue,
            spacing_size=spacing_size,
            radius_size=radius_size,
            text_size=text_size,
        )
        super().set(
            color_body_background_dark="*primary_800",
            color_background_secondary_dark="*primary_800",
            color_background_tertiary_dark="*primary_800",
            button_primary_background_base="linear-gradient(180deg, *primary_50 0%, *primary_200 50%, *primary_300 50%, *primary_200 100%)",
            button_primary_background_hover="linear-gradient(180deg, *primary_100 0%, *primary_200 50%, *primary_300 50%, *primary_200 100%)",
            button_primary_background_base_dark="linear-gradient(180deg, *primary_400 0%, *primary_500 50%, *primary_600 50%, *primary_500 100%)",
            button_primary_background_hover_dark="linear-gradient(180deg, *primary_400 0%, *primary_500 50%, *primary_600 50%, *primary_500 100%)",
            button_secondary_background_base="*button_primary_background_base",
            button_secondary_background_hover="*button_primary_background_hover",
            button_secondary_background_base_dark="*button_primary_background_base",
            button_secondary_background_hover_dark="*button_primary_background_hover",
            button_cancel_background_base="*button_primary_background_base",
            button_cancel_background_hover="*button_primary_background_hover",
            button_cancel_background_base_dark="*button_primary_background_base",
            button_cancel_background_hover_dark="*button_primary_background_hover",
            button_cancel_border_color_base="*button_secondary_border_color_base",
            button_cancel_border_color_base_dark="*button_secondary_border_color_base",
            button_cancel_text_color_base="*button_secondary_text_color_base",
            checkbox_border_width="0px",
            checkbox_label_background_base="*button_secondary_background_base",
            checkbox_label_background_base_dark="*button_secondary_background_base",
            checkbox_label_background_hover="*button_secondary_background_hover",
            checkbox_label_background_hover_dark="*button_secondary_background_hover",
            checkbox_label_border_width="1px",
            checkbox_background_base_dark="*primary_600",
            button_border_width="1px",
            button_shadow_active="*shadow_inset",
            input_background_base="linear-gradient(0deg, *secondary_50 0%, white 100%)",
            input_background_base_dark="*secondary_600",
            input_border_width="1px",
            slider_color="*primary_400",
            block_label_color="*primary_500",
            block_label_text_weight="600",
            block_title_text_weight="600",
            block_label_text_size="*text_md",
            block_title_text_size="*text_md",
            block_label_background="*primary_200",
            block_label_background_dark="*primary_700",
            block_border_width="0px",
            block_border_width_dark="1px",
            panel_border_width="1px",
            color_border_primary_dark="*primary_500",
            color_background_primary_dark="*neutral_700",
            color_background_secondary="*primary_100",
            color_background_tertiary="*primary_50",
            block_shadow="*primary_400 0px 0px 3px 0px",
            table_even_background_dark="*neutral_700",
            table_odd_background_dark="*neutral_700",
        )
