from __future__ import annotations

from collections.abc import Iterable

from gradio.themes.base import Base
from gradio.themes.utils import colors, fonts, sizes


class Noir(Base):
    def __init__(
        self,
        *,
        primary_hue: colors.Color | str = colors.stone,
        secondary_hue: colors.Color | str = colors.stone,
        neutral_hue: colors.Color | str = colors.stone,
        spacing_size: sizes.Size | str = sizes.spacing_md,
        radius_size: sizes.Size | str = sizes.radius_sm,
        text_size: sizes.Size | str = sizes.text_md,
        font: fonts.Font | str | Iterable[fonts.Font | str] = (
            fonts.GoogleFont("DM Sans"),
            "ui-sans-serif",
            "system-ui",
            "sans-serif",
        ),
        font_mono: fonts.Font | str | Iterable[fonts.Font | str] = (
            fonts.GoogleFont("JetBrains Mono"),
            "ui-monospace",
            "Consolas",
            "monospace",
        ),
    ):
        super().__init__(
            primary_hue=primary_hue,
            secondary_hue=secondary_hue,
            neutral_hue=neutral_hue,
            spacing_size=spacing_size,
            radius_size=radius_size,
            text_size=text_size,
            font=font,
            font_mono=font_mono,
        )
        self.name = "noir"
        super().set(
            # Body
            body_background_fill="*neutral_50",
            body_background_fill_dark="*neutral_950",
            body_text_color="*neutral_800",
            body_text_color_dark="*neutral_200",
            body_text_color_subdued="*neutral_500",
            body_text_color_subdued_dark="*neutral_400",
            # Backgrounds
            background_fill_primary="white",
            background_fill_primary_dark="*neutral_900",
            background_fill_secondary="*neutral_100",
            background_fill_secondary_dark="*neutral_800",
            # Shadows
            shadow_drop="0 1px 3px 0 rgb(0 0 0 / 0.06), 0 1px 2px -1px rgb(0 0 0 / 0.06)",
            shadow_drop_lg="0 4px 6px -1px rgb(0 0 0 / 0.07), 0 2px 4px -2px rgb(0 0 0 / 0.07)",
            shadow_spread="3px",
            # Blocks
            block_background_fill="white",
            block_background_fill_dark="*neutral_900",
            block_border_width="1px",
            block_border_color="*neutral_200",
            block_border_color_dark="*neutral_700",
            block_shadow="*shadow_drop",
            block_shadow_dark="none",
            block_label_background_fill="*neutral_100",
            block_label_background_fill_dark="*neutral_800",
            block_label_text_color="*neutral_600",
            block_label_text_color_dark="*neutral_300",
            block_label_text_weight="600",
            block_label_text_size="*text_sm",
            block_label_padding="*spacing_sm *spacing_md",
            block_label_radius="*radius_sm",
            block_title_background_fill="*neutral_100",
            block_title_background_fill_dark="*neutral_800",
            block_title_text_color="*neutral_600",
            block_title_text_color_dark="*neutral_300",
            block_title_text_weight="600",
            block_title_padding="*spacing_sm *spacing_md",
            # Inputs
            input_background_fill="white",
            input_background_fill_dark="*neutral_800",
            input_border_color="*neutral_200",
            input_border_color_dark="*neutral_600",
            input_border_width="1px",
            input_shadow="none",
            input_shadow_focus="0 0 0 2px *secondary_200",
            input_shadow_focus_dark="0 0 0 2px *secondary_800",
            input_border_color_focus="*secondary_400",
            input_border_color_focus_dark="*secondary_600",
            # Buttons
            button_border_width="1px",
            button_transition="all 0.15s ease",
            button_primary_background_fill="*neutral_800",
            button_primary_background_fill_dark="*neutral_100",
            button_primary_background_fill_hover="*neutral_700",
            button_primary_background_fill_hover_dark="*neutral_200",
            button_primary_text_color="white",
            button_primary_text_color_dark="*neutral_900",
            button_primary_border_color="*neutral_800",
            button_primary_border_color_dark="*neutral_100",
            button_primary_shadow="none",
            button_primary_shadow_hover="*shadow_drop",
            button_primary_shadow_active="none",
            button_secondary_background_fill="white",
            button_secondary_background_fill_dark="*neutral_800",
            button_secondary_background_fill_hover="*neutral_50",
            button_secondary_background_fill_hover_dark="*neutral_700",
            button_secondary_text_color="*neutral_700",
            button_secondary_text_color_dark="*neutral_200",
            button_secondary_border_color="*neutral_200",
            button_secondary_border_color_dark="*neutral_600",
            button_secondary_shadow="none",
            button_cancel_background_fill="white",
            button_cancel_background_fill_dark="*neutral_800",
            button_cancel_background_fill_hover="*secondary_50",
            button_cancel_background_fill_hover_dark="*secondary_900",
            button_cancel_text_color="*secondary_600",
            button_cancel_text_color_dark="*secondary_400",
            button_cancel_border_color="*secondary_200",
            button_cancel_border_color_dark="*secondary_800",
            # Checkboxes
            checkbox_background_color_selected="*neutral_800",
            checkbox_background_color_selected_dark="*neutral_600",
            checkbox_border_color="*neutral_300",
            checkbox_border_color_dark="*neutral_500",
            checkbox_border_color_selected="*neutral_800",
            checkbox_border_color_selected_dark="*neutral_600",
            checkbox_shadow="none",
            checkbox_label_background_fill="white",
            checkbox_label_background_fill_dark="*neutral_800",
            checkbox_label_background_fill_selected="*neutral_800",
            checkbox_label_background_fill_selected_dark="*neutral_200",
            checkbox_label_text_color_selected="white",
            checkbox_label_text_color_selected_dark="*neutral_900",
            checkbox_label_shadow="none",
            checkbox_label_border_width="1px",
            checkbox_label_border_color="*neutral_200",
            checkbox_label_border_color_dark="*neutral_600",
            # Slider
            slider_color="*neutral_800",
            slider_color_dark="*neutral_300",
            # Color accents
            color_accent="*secondary_500",
            color_accent_soft="*secondary_50",
            color_accent_soft_dark="*secondary_900",
            # Tables
            table_even_background_fill="*neutral_50",
            table_even_background_fill_dark="*neutral_800",
            table_odd_background_fill="white",
            table_odd_background_fill_dark="*neutral_900",
            table_row_focus="*neutral_200",
            table_row_focus_dark="*neutral_700",
            # Panels
            panel_border_width="1px",
        )
