export const redirects = {
	"/guides/creating-a-new-component":
		"/guides/custom-components-in-five-minutes",
	"/guides/five-minute-guide": "/guides/custom-components-in-five-minutes",
	"/controlling-layout": "/guides/controlling-layout",
	"/state-in-blocks": "/guides/state-in-blocks",
	"/custom-CSS-and-JS": "/guides/custom-CSS-and-JS",
	"/blocks-and-event-listeners": "/guides/blocks-and-event-listeners",
	"/using-blocks-like-functions": "/guides/using-blocks-like-functions",
	"/using-flagging": "/guides/using-flagging",
	"/named-entity-recognition": "/guides/named-entity-recognition",
	"/real-time-speech-recognition": "/guides/real-time-speech-recognition",
	"/developing-faster-with-reload-mode":
		"/guides/developing-faster-with-reload-mode",
	"/create-your-own-friends-with-a-gan":
		"/guides/create-your-own-friends-with-a-gan",
	"/setting-up-a-demo-for-maximum-performance":
		"/guides/setting-up-a-demo-for-maximum-performance",
	"/creating-a-chatbot": "/guides/creating-a-chatbot-fast",
	"/guides/creating-a-chatbot": "/guides/creating-a-chatbot-fast",
	"/how-to-use-3D-model-component": "/guides/how-to-use-3D-model-component",
	"/creating-a-new-component": "/guides/creating-a-new-component",
	"/running-background-tasks": "/guides/running-background-tasks",
	"/reactive-interfaces": "/guides/reactive-interfaces",
	"/four-kinds-of-interfaces": "/guides/four-kinds-of-interfaces",
	"/interface-state": "/guides/interface-state",
	"/more-on-examples": "/guides/more-on-examples",
	"/advanced-interface-features": "/3.50.2/guides/advanced-interface-features",
	"/guides/advanced-interface-features":
		"/3.50.2/guides/advanced-interface-features",
	"/key-features": "/guides/key-features",
	"/quickstart": "/guides/quickstart",
	"/sharing-your-app": "/guides/sharing-your-app",
	"/connecting-to-a-database": "/guides/connecting-to-a-database",
	"/creating-a-realtime-dashboard-from-google-sheets":
		"/guides/creating-a-realtime-dashboard-from-google-sheets",
	"/plot-component-for-maps": "/guides/plot-component-for-maps",
	"/creating-a-dashboard-from-bigquery-data":
		"/guides/creating-a-dashboard-from-bigquery-data",
	"/using-gradio-for-tabular-workflows":
		"/guides/using-gradio-for-tabular-workflows",
	"/image-classification-in-pytorch": "/guides/image-classification-in-pytorch",
	"/using-hugging-face-integrations": "/guides/using-hugging-face-integrations",
	"/Gradio-and-ONNX-on-Hugging-Face": "/guides/Gradio-and-ONNX-on-Hugging-Face",
	"/image-classification-with-vision-transformers":
		"/guides/image-classification-with-vision-transformers",
	"/Gradio-and-Wandb-Integration": "/guides/Gradio-and-Wandb-Integration",
	"/image-classification-in-tensorflow":
		"/guides/image-classification-in-tensorflow",
	"/Gradio-and-Comet": "/guides/Gradio-and-Comet",
	"/introduction_to_blocks": "/guides/blocks-and-event-listeners",
	"/adding_examples_to_your_app": "/guides/key-features",
	"/embedding_gradio_demos": "/guides/sharing-your-app",
	"/getting_started": "/guides/quickstart",
	"/building_with_blocks": "/guides/blocks-and-event-listeners",
	"/guides/building-with-blocks": "/guides/blocks-and-event-listeners",
	"/building_interfaces": "/guides/interface-state",
	"/guides/building-interfaces": "/guides/interface-state",
	"/tabular_data_science_and_plots": "/guides/connecting-to-a-database",
	"/guides/tabular-data-science-and-plots": "/guides/connecting-to-a-database",
	"/integrating_other_frameworks": "/guides/using-hugging-face-integrations",
	"/guides/integrating-other-frameworks":
		"/guides/using-hugging-face-integrations",
	"/controlling_layout": "/guides/controlling-layout",
	"/state_in_blocks": "/guides/state-in-blocks",
	"/custom_CSS_and_JS": "/guides/custom-CSS-and-JS",
	"/blocks_and_event_listeners": "/guides/blocks-and-event-listeners",
	"/using_blocks_like_functions": "/guides/using-blocks-like-functions",
	"/using_flagging": "/guides/using-flagging",
	"/named_entity_recognition": "/guides/named-entity-recognition",
	"/real_time_speech_recognition": "/guides/real-time-speech-recognition",
	"/developing_faster_with_reload_mode":
		"/guides/developing-faster-with-reload-mode",
	"/create_your_own_friends_with_a_gan":
		"/guides/create-your-own-friends-with-a-gan",
	"/setting_up_a_demo_for_maximum_performance":
		"/guides/setting-up-a-demo-for-maximum-performance",
	"/creating_a_chatbot": "/guides/creating-a-chatbot",
	"/how_to_use_3D_model_component": "/guides/how-to-use-3D-model-component",
	"/creating_a_new_component": "/guides/creating-a-new-component",
	"/running_background_tasks": "/guides/running-background-tasks",
	"/reactive_interfaces": "/guides/reactive-interfaces",
	"/more_on_examples_and_flagging": "/guides/more-on-examples",
	"/interface_state": "/guides/interface-state",
	"/key_features": "/guides/key-features",
	"/sharing_your_app": "/guides/sharing-your-app",
	"/connecting_to_a_database": "/guides/connecting-to-a-database",
	"/creating_a_realtime_dashboard_from_google_sheets":
		"/guides/creating-a-realtime-dashboard-from-google-sheets",
	"/plot_component_for_maps": "/guides/plot-component-for-maps",
	"/creating_a_dashboard_from_bigquery_data":
		"/guides/creating-a-dashboard-from-bigquery-data",
	"/using_gradio_for_tabular_workflows":
		"/guides/using-gradio-for-tabular-workflows",
	"/image_classification_in_pytorch": "/guides/image-classification-in-pytorch",
	"/using_hugging_face_integrations": "/guides/using-hugging-face-integrations",
	"/Gradio_and_ONNX_on_Hugging_Face": "/guides/Gradio-and-ONNX-on-Hugging-Face",
	"/image_classification_with_vision_transformers":
		"/guides/image-classification-with-vision-transformers",
	"/Gradio_and_Wandb_Integration": "/guides/Gradio-and-Wandb-Integration",
	"/image_classification_in_tensorflow":
		"/guides/image-classification-in-tensorflow",
	"/demos": "/playground",
	"/getting-started-with-the-python-client":
		"/guides/getting-started-with-the-python-client",
	"/getting-started-with-the-js-client":
		"/guides/getting-started-with-the-js-client",
	"/gradio-and-llm-agents": "/guides/gradio-and-llm-agents",
	"/fastapi-app-with-the-gradio-client":
		"/guides/fastapi-app-with-the-gradio-client",
	"/docs/client": "/docs/python-client/client",
	"/docs/job": "/docs/python-client/job",
	"/docs/set_static_paths": "/docs/gradio/set_static_paths",
	"/docs/eventdata": "/docs/gradio/eventdata",
	"/docs/examples": "/docs/gradio/examples",
	"/docs/progress": "/docs/gradio/progress",
	"/docs/make_waveform": "/docs/gradio/make_waveform",
	"/docs/load": "/docs/gradio/load",
	"/docs/error": "/docs/gradio/error",
	"/docs/warning": "/docs/gradio/warning",
	"/docs/info": "/docs/gradio/info",
	"/docs/flagging": "/docs/gradio/flagging",
	"/docs/request": "/docs/gradio/request",
	"/docs/mount_gradio_app": "/docs/gradio/mount_gradio_app",
	"/docs/base": "/docs/gradio/base",
	"/docs/queue": "/docs/gradio/queue",
	"/docs/blocks": "/docs/gradio/blocks",
	"/docs/accordion": "/docs/gradio/accordion",
	"/docs/column": "/docs/gradio/column",
	"/docs/row": "/docs/gradio/row",
	"/docs/group": "/docs/gradio/group",
	"/docs/tab": "/docs/gradio/tab",
	"/docs/annotatedimage": "/docs/gradio/annotatedimage",
	"/docs/audio": "/docs/gradio/audio",
	"/docs/barplot": "/docs/gradio/barplot",
	"/docs/button": "/docs/gradio/button",
	"/docs/chatbot": "/docs/gradio/chatbot",
	"/docs/checkbox": "/docs/gradio/checkbox",
	"/docs/checkboxgroup": "/docs/gradio/checkboxgroup",
	"/docs/clearbutton": "/docs/gradio/clearbutton",
	"/docs/code": "/docs/gradio/code",
	"/docs/colorpicker": "/docs/gradio/colorpicker",
	"/docs/dataframe": "/docs/gradio/dataframe",
	"/docs/dataset": "/docs/gradio/dataset",
	"/docs/downloadbutton": "/docs/gradio/downloadbutton",
	"/docs/dropdown": "/docs/gradio/dropdown",
	"/docs/duplicatebutton": "/docs/gradio/duplicatebutton",
	"/docs/file": "/docs/gradio/file",
	"/docs/fileexplorer": "/docs/gradio/fileexplorer",
	"/docs/gallery": "/docs/gradio/gallery",
	"/docs/html": "/docs/gradio/html",
	"/docs/highlightedtext": "/docs/gradio/highlightedtext",
	"/docs/image": "/docs/gradio/image",
	"/docs/imageeditor": "/docs/gradio/imageeditor",
	"/docs/json": "/docs/gradio/json",
	"/docs/label": "/docs/gradio/label",
	"/docs/lineplot": "/docs/gradio/lineplot",
	"/docs/loginbutton": "/docs/gradio/loginbutton",
	"/docs/logoutbutton": "/docs/gradio/logoutbutton",
	"/docs/markdown": "/docs/gradio/markdown",
	"/docs/model3d": "/docs/gradio/model3d",
	"/docs/multimodaltextbox": "/docs/gradio/multimodaltextbox",
	"/docs/number": "/docs/gradio/number",
	"/docs/paramviewer": "/docs/gradio/paramviewer",
	"/docs/plot": "/docs/gradio/plot",
	"/docs/radio": "/docs/gradio/radio",
	"/docs/scatterplot": "/docs/gradio/scatterplot",
	"/docs/simpleimage": "/docs/gradio/simpleimage",
	"/docs/slider": "/docs/gradio/slider",
	"/docs/state": "/docs/gradio/state",
	"/docs/textbox": "/docs/gradio/textbox",
	"/docs/uploadbutton": "/docs/gradio/uploadbutton",
	"/docs/video": "/docs/gradio/video",
	"/docs/chatinterface": "/docs/gradio/chatinterface",
	"/docs/interface": "/docs/gradio/interface",
	"/docs/tabbedinterface": "/docs/gradio/tabbedinterface",
	"/docs/themes": "/docs/gradio/themes",
	"/docs/no-reload": "/docs/gradio/no-reload",
	"/docs/python-client/python-client": "/docs/python-client/intro",
	"/docs/python-client/js-client": "/docs/js-client",
	"/3.50.2/docs/python-client/python-client": "/docs/python-client/intro",
	"/3.50.2/docs/python-client/js-client": "/docs/js-client"
};
