name: "install frontend"
description: "Install frontend deps"

inputs:
  skip_build:
    description: "Skip build"
    default: "false"

runs:
  using: "composite"
  steps:
    - uses: actions/cache@v4
      id: frontend-core-cache
      if: inputs.skip_build == 'false'
      with:
        path: |
          gradio/templates/**
        key: gradio-lib-front-end-${{ hashFiles('js/**', 'client/js/**')}}
    - name: Install pnpm
      uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # @v4
      with:
        version: 9.1.x
    - uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: pnpm
        cache-dependency-path: pnpm-lock.yaml
    - name: Install deps
      shell: bash
      run: pnpm i --frozen-lockfile --ignore-scripts
    - name: Build Css
      shell: bash
      run: pnpm css
    - name: Build frontend
      if: inputs.skip_build == 'false' && steps.frontend-core-cache.outputs.cache-hit != 'true'
      shell: bash
      run: pnpm build
