import gradio as gr


with gr.Blocks() as demo:
    gr.AnnotatedImage()
    # gr.AnnotatedImage(interactive=True)
    gr.Audio(interactive=False)
    gr.Audio(interactive=True)
    gr.BarPlot(interactive=False)
    gr.BarPlot(interactive=True)
    gr.Button(interactive=False)
    gr.Button(interactive=True)
    gr.Chatbot()
    # gr.Chatbot(interactive=True)
    gr.Checkbox(interactive=False)
    gr.Checkbox(interactive=True)
    gr.CheckboxGroup(interactive=False)
    gr.CheckboxGroup(interactive=True)
    gr.ClearButton(interactive=False)
    gr.ClearButton(interactive=True)
    gr.Code(interactive=False)
    gr.Code(interactive=True)
    gr.ColorPicker(interactive=False)
    gr.ColorPicker(interactive=True)
    gr.Dataframe(interactive=False)
    gr.Dataframe(interactive=True)
    gr.Dataset()
    # gr.Dataset(interactive=True)
    gr.DateTime()
    # gr.DateTime(interactive=True)
    gr.DownloadButton(interactive=False)
    gr.DownloadButton(interactive=True)
    gr.Dropdown(interactive=False)
    gr.Dropdown(interactive=True)
    gr.DuplicateButton(interactive=False)
    gr.DuplicateButton(interactive=True)
    gr.File()
    gr.File(interactive=True)
    gr.FileExplorer(interactive=False)
    gr.FileExplorer(interactive=True)
    gr.Gallery(interactive=False)
    gr.Gallery(interactive=True)
    gr.HighlightedText(interactive=False)
    gr.HighlightedText(interactive=True)
    gr.HTML()
    # gr.HTML(interactive=True)
    gr.Image(interactive=False)
    gr.Image(interactive=True)
    gr.ImageEditor(interactive=False)
    gr.ImageEditor(interactive=True)
    gr.JSON()
    # gr.JSON(interactive=True)
    gr.Label()
    # gr.Label(interactive=True)
    gr.LinePlot(interactive=False)
    gr.LinePlot(interactive=True)
    # gr.LoginButton()
    # gr.LoginButton(interactive=True)
    # gr.LogoutButton()
    # gr.LogoutButton(interactive=True)
    gr.Markdown()
    # gr.Markdown(interactive=True)
    gr.Model3D(interactive=False)
    gr.Model3D(interactive=True)
    gr.MultimodalTextbox(interactive=False)
    gr.MultimodalTextbox(interactive=True)
    gr.Number()
    gr.Number(interactive=True)
    gr.ParamViewer()
    # gr.ParamViewer(interactive=True)
    gr.Plot()
    # gr.Plot(interactive=True)
    gr.Radio(interactive=False)
    gr.Radio(interactive=True)
    gr.ScatterPlot(interactive=False)
    gr.ScatterPlot(interactive=True)
    # gr.SimpleImage()
    # gr.SimpleImage(interactive=True)
    gr.Slider(interactive=False)
    gr.Slider(interactive=True)
    gr.State()
    # gr.State(interactive=True)
    gr.Textbox(interactive=False)
    gr.Textbox(interactive=True)
    gr.Timer()
    # gr.Timer(interactive=True)
    gr.UploadButton()
    gr.UploadButton(interactive=True)
    gr.Video(interactive=False)
    gr.Video(interactive=True)


if __name__ == "__main__":
    demo.launch()
