name: "docs-build"

on:
  pull_request:
  push:
    branches:
      - main
      - 5.0-dev

env:
  CI: true
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"
  NODE_OPTIONS: "--max-old-space-size=4096"

concurrency:
  group: "${{ github.event.pull_request.number }}-${{ github.ref_name }}-${{ github.workflow }}"
  cancel-in-progress: true

permissions: {}

jobs:
  changes:
    if: github.event_name == 'pull_request' || github.event_name == 'push'
    permissions:
      contents: read
      pull-requests: read
    name: "changes"
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.changes.outputs.should_run }}
      sha: ${{ steps.changes.outputs.sha }}
      gradio_version: ${{ steps.changes.outputs.gradio_version }}
      source_branch: ${{ steps.changes.outputs.source_branch }}
    steps:
      - uses: actions/checkout@v4
      - uses: "gradio-app/gradio/.github/actions/changes@main"
        id: changes
        with:
          filter: "website"
          token: ${{ secrets.GITHUB_TOKEN }}

  build:
    permissions:
      contents: read
    name: "docs-build"
    runs-on: ubuntu-22.04
    needs: changes
    if: needs.changes.outputs.should_run == 'true' || (endsWith(needs.changes.outputs.source_branch, 'main') && github.repository == 'gradio-app/gradio')
    steps:
      - uses: actions/checkout@v4
      - name: install dependencies
        uses: "gradio-app/gradio/.github/actions/install-all-deps@main"
        with:
          python_version: "3.10"
          skip_build: true
          test: true

        # generated when installing deps
      - name: upload website json artifacts
        uses: actions/upload-artifact@v4
        with:
          name: website-json
          path: js/_website/src/lib/json
      - name: upload website json templates
        uses: actions/upload-artifact@v4
        with:
          name: website-templates
          path: js/_website/src/lib/templates
